[package]
name = "dsss_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
hound = "3"
image = "0.24"
rand = "0.8"
rand_chacha = "0.3"
reed-solomon = "0.2"
rustfft = "6"

