[package]
name = "dsss_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
clap = { version = "4", features = ["derive", "env"] }
hound = "3"
rustfft = "6"
image = "0.24"

